### ISSUE TITLE
Lines 196-205: cohesinKO.main.R script

### ISSUE THREAD

**Issue by dpolychr** [ibn-salem/cohesinKO#7]
The following warning comes up:

Warning messages:
1: attributes are not identical across measure variables; they will be dropped 
2: Too many values at 3998268 locations: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18#, 19, 20, ...

**Comment by ibn-salem** [comment]
Thanks Dimitirs for reporting this.
The first warning results from 'tidyr::gather()' because factor and integer columns are merged into one column and result in character type. This should not be a problem for downstream analysis.
The second warning is fixed in commit 947add495176ff5766d1e270c23a8691a902c11d
